{ lib, pkgs, config, ... }:
with lib;
{
  shellAliases = {
    qinstall = "nix-env -iA";
    quninstall = "nix-env -e";
    qbuild = "sudo cp -r ~/nixos /etc; and sudo nixos-rebuild switch";
    qrollback = "sudo nixos-rebuild switch --rollback";

    qlsgenerations = "nix-env --list-generations";

    qlspkgs = "cat /tmp/nix-list-pkgs | fzf --reverse --ansi";  # generated by quasar-nixlist-pkgs.service
    qlsopts = "man configuration.nix | grep -v '^        ' | grep -v '^[ \\r\\n\\t]*$' | fzfr";
    qlshomeopts = "man home-configuration.nix | grep -v '^        ' | grep -v '^[ \\r\\n\\t]*$' | fzfr";
    qlsinstalled = "nix-env -q";
    qlssyspkgs = "sudo nixos-option environment.systemPackages";

    qgc = "nix-collect-garbage --delete-older-than 3d";
    qgc1 = "nix-collect-garbage --delete-older-than 1d";
    qgcd = "nix-collect-garbage --delete-older-than";
    qgcforce = "nix-collect-garbage -d";
    qoptstore = "nix-store --optimise -v";
    
    qsvstop = "sudo systemctl stop";
    qsvstart = "sudo systemctl start";
    qsvstatus = "sudo systemctl status";
    qsvcat = "sudo systemctl cat";
    qsustop = "systemctl --user stop";
    qsustart = "systemctl --user start";
    qsustatus = "systemctl --user status";
    qsucat = "systemctl --user cat";

    qlssv = "systemctl list-unit-files | fzfr";
    qlssu = "systemctl list-unit-files | grep quasar- | fzfr";
  };
  shellInit =
    ''
      function qsvrestart
        sudo systemctl restart $argv
        or systemctl status $argv
      end

      function qsurestart
        systemctl --user restart $argv
        or systemctl --user status $argv
      end

      function nix-shell-fish
        fish-nix-shell-wrapper $argv
        set -gx FISH_NIX_SHELL_EXIT_STATUS $status
      end
    '';
}